baseURL = 'https://maxdesalle.com/'
languageCode = 'en-us'
title = 'Maxime Desalle'

[params]
  description = "Win and help win. Studying math, physics and computers.\n\n**Life mission**: make the universe better for all of consciousness."
  dark = "off"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "resources"
    name = "resources"
    title = "resources"
    url = "/resources/"
    weight = 10

  [[menu.socials]]
    identifier = "twitter"
    name = "twitter"
    title = "twitter"
    url = "https://twitter.com/maxdesalle"
    weight = 30

  [[menu.socials]]
    identifier = "github"
    name = "github"
    title = "github"
    url = "https://github.com/maxdesalle"
    weight = 40
