baseURL = "https://maxdesalle.com/"
languageCode = "en-us"
title = "Maxime Desalle"
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  # description = "Win and help win."
  dark = "off"
  highlight = true
  # images = ["https://maxdesalle.com/social_image.jpg"]

[menu]
  [[menu.main]]
    identifier = "startup ideas"
    name = "startup ideas"
    title = "startup ideas"
    url = "/startup-ideas/"
    weight = 10

  [[menu.main]]
    identifier = "resources"
    name = "resources"
    title = "resources"
    url = "/resources/"
    weight = 20

  [[menu.socials]]
    identifier = "twitter"
    name = "twitter"
    title = "twitter"
    url = "https://twitter.com/maxdesalle"
    weight = 30

  [[menu.socials]]
    identifier = "github"
    name = "github"
    title = "github"
    url = "https://github.com/maxdesalle"
    weight = 40

  # [[menu.socials]]
  #   identifier = "signal"
  #   name = "signal"
  #   title = "signal"
  #   url = "https://signal.me/#eu/TST_2FkJznjly3Xkn2NnsNRDw32eoOTHwO0L9REt2N1A2fOQ_vdKEYb-C-KsvEW6"
  #   weight = 50

[permalinks]
  posts = "/:filename/"

[markup.goldmark.renderer]
  unsafe = true
