baseURL = "https://maxdesalle.com"
title = "Maxime Desalle"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Reading, thinking, writing and coding."
  copyright = "Reading, thinking, writing and coding."
  dark = "off"
  highlight = true
  images = ["https://images.unsplash.com/photo-1518972734183-c5b490a7c637?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80"]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "home"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "books"
    name = "books"
    title = "books"
    url = "/books/"
    weight = 20

  [[menu.main]]
    identifier = "twitter"
    name = "twitter"
    title = "twitter"
    url = "https://twitter.com/maxdesalle"
    weight = 30

[permalinks]
  posts = "/:filename/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
