baseURL = "https://maxdesalle.com/"
languageCode = "en-us"
title = "Maxime Desalle"
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  # description = "Win and help win."
  dark = "off"
  highlight = true
  math = true
  # images = ["https://maxdesalle.com/social_image.jpg"]

[menu]
  [[menu.main]]
    identifier = "startup ideas"
    name = "startup ideas"
    title = "startup ideas"
    url = "/startup-ideas/"
    weight = 5

  [[menu.main]]
    identifier = "piano"
    name = "piano"
    title = "piano"
    url = "/piano/"
    weight = 10

  [[menu.main]]
    identifier = "photography"
    name = "photography"
    title = "photography"
    url = "/photography/"
    weight = 15

  [[menu.main]]
    identifier = "resources"
    name = "resources"
    title = "resources"
    url = "/resources/"
    weight = 20

  [[menu.socials]]
    identifier = "twitter"
    name = "twitter"
    title = "twitter"
    url = "https://twitter.com/maxdesalle"
    weight = 25

  [[menu.socials]]
    identifier = "github"
    name = "github"
    title = "github"
    url = "https://github.com/maxdesalle"
    weight = 30

[permalinks]
  posts = "/:filename/"

[markup]
  [markup.goldmark]
		[markup.goldmark.parser]
			attribute = true
		[markup.goldmark.renderer]
			unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
