baseURL = "https://maxdesalle.com"
title = "Maxime Desalle"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Reading, thinking, writing and coding."
  dark = "off"
  highlight = true
  images = ["https://maxdesalle.com/maxime-desalle.jpg"]

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "posts"
    title = "posts"
    url = "/blog/"
    weight = 10

  [[menu.main]]
    identifier = "books"
    name = "books"
    title = "books"
    url = "/books/"
    weight = 20

  [[menu.main]]
    identifier = "rss"
    name = "rss"
    title = "rss"
    url = "/index.xml/"
    weight = 30

[permalinks]
  posts = "/:filename/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
